# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qwordnotify.ui'
#
# Created: Sun Jul 20 16:02:24 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(384, 254)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.dictGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.dictGroupBox.setObjectName(_fromUtf8("dictGroupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dictGroupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.dictListView = QtGui.QListView(self.dictGroupBox)
        self.dictListView.setObjectName(_fromUtf8("dictListView"))
        self.horizontalLayout_2.addWidget(self.dictListView)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.dictNewPushButton = QtGui.QPushButton(self.dictGroupBox)
        self.dictNewPushButton.setObjectName(_fromUtf8("dictNewPushButton"))
        self.verticalLayout_6.addWidget(self.dictNewPushButton)
        self.dictAddPushButton = QtGui.QPushButton(self.dictGroupBox)
        self.dictAddPushButton.setObjectName(_fromUtf8("dictAddPushButton"))
        self.verticalLayout_6.addWidget(self.dictAddPushButton)
        self.dictEditPushButton = QtGui.QPushButton(self.dictGroupBox)
        self.dictEditPushButton.setObjectName(_fromUtf8("dictEditPushButton"))
        self.verticalLayout_6.addWidget(self.dictEditPushButton)
        self.dictRemovePushButton = QtGui.QPushButton(self.dictGroupBox)
        self.dictRemovePushButton.setObjectName(_fromUtf8("dictRemovePushButton"))
        self.verticalLayout_6.addWidget(self.dictRemovePushButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line = QtGui.QFrame(self.dictGroupBox)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.optionsPushButton = QtGui.QPushButton(self.dictGroupBox)
        self.optionsPushButton.setObjectName(_fromUtf8("optionsPushButton"))
        self.horizontalLayout.addWidget(self.optionsPushButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.stopPushButton = QtGui.QPushButton(self.dictGroupBox)
        self.stopPushButton.setObjectName(_fromUtf8("stopPushButton"))
        self.horizontalLayout.addWidget(self.stopPushButton)
        self.startPushButton = QtGui.QPushButton(self.dictGroupBox)
        self.startPushButton.setObjectName(_fromUtf8("startPushButton"))
        self.horizontalLayout.addWidget(self.startPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.dictGroupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 384, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuDict = QtGui.QMenu(self.menubar)
        self.menuDict.setObjectName(_fromUtf8("menuDict"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        MainWindow.setMenuBar(self.menubar)
        self.actionStart = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("icons/start.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStart.setIcon(icon1)
        self.actionStart.setIconVisibleInMenu(True)
        self.actionStart.setObjectName(_fromUtf8("actionStart"))
        self.actionQuit = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("icons/exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon2)
        self.actionQuit.setIconVisibleInMenu(True)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("icons/preferences.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPreferences.setIcon(icon3)
        self.actionPreferences.setIconVisibleInMenu(True)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionNew = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("icons/new.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon4)
        self.actionNew.setIconVisibleInMenu(True)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionEdit = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("icons/edit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEdit.setIcon(icon5)
        self.actionEdit.setIconVisibleInMenu(True)
        self.actionEdit.setObjectName(_fromUtf8("actionEdit"))
        self.actionRemove = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("icons/remove.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRemove.setIcon(icon6)
        self.actionRemove.setIconVisibleInMenu(True)
        self.actionRemove.setObjectName(_fromUtf8("actionRemove"))
        self.actionAbout = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("icons/help.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon7)
        self.actionAbout.setIconVisibleInMenu(True)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionAbout_Qt = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("icons/qt.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout_Qt.setIcon(icon8)
        self.actionAbout_Qt.setIconVisibleInMenu(True)
        self.actionAbout_Qt.setObjectName(_fromUtf8("actionAbout_Qt"))
        self.actionStop = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("icons/stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon9)
        self.actionStop.setIconVisibleInMenu(True)
        self.actionStop.setObjectName(_fromUtf8("actionStop"))
        self.actionShowHide = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8("icons/showhide.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShowHide.setIcon(icon10)
        self.actionShowHide.setIconVisibleInMenu(True)
        self.actionShowHide.setObjectName(_fromUtf8("actionShowHide"))
        self.actionHide = QtGui.QAction(MainWindow)
        self.actionHide.setObjectName(_fromUtf8("actionHide"))
        self.actionAdd = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8("icons/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd.setIcon(icon11)
        self.actionAdd.setIconVisibleInMenu(True)
        self.actionAdd.setObjectName(_fromUtf8("actionAdd"))
        self.menuFile.addAction(self.actionStart)
        self.menuFile.addAction(self.actionStop)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionShowHide)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionPreferences)
        self.menuDict.addAction(self.actionNew)
        self.menuDict.addAction(self.actionAdd)
        self.menuDict.addAction(self.actionEdit)
        self.menuDict.addAction(self.actionRemove)
        self.menuAbout.addAction(self.actionAbout)
        self.menuAbout.addAction(self.actionAbout_Qt)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuDict.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "qWordNotify", None))
        self.dictGroupBox.setTitle(_translate("MainWindow", "Dictionaries:", None))
        self.dictNewPushButton.setText(_translate("MainWindow", "New", None))
        self.dictAddPushButton.setText(_translate("MainWindow", "Add", None))
        self.dictEditPushButton.setText(_translate("MainWindow", "Edit", None))
        self.dictRemovePushButton.setText(_translate("MainWindow", "Remove", None))
        self.optionsPushButton.setText(_translate("MainWindow", "Options", None))
        self.stopPushButton.setText(_translate("MainWindow", "Stop", None))
        self.startPushButton.setText(_translate("MainWindow", "Start", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.menuDict.setTitle(_translate("MainWindow", "Dict", None))
        self.menuAbout.setTitle(_translate("MainWindow", "Help", None))
        self.actionStart.setText(_translate("MainWindow", "Start", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences", None))
        self.actionNew.setText(_translate("MainWindow", "New", None))
        self.actionEdit.setText(_translate("MainWindow", "Edit", None))
        self.actionRemove.setText(_translate("MainWindow", "Remove", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionAbout_Qt.setText(_translate("MainWindow", "About Qt", None))
        self.actionStop.setText(_translate("MainWindow", "Stop", None))
        self.actionShowHide.setText(_translate("MainWindow", "Show/Hide", None))
        self.actionHide.setText(_translate("MainWindow", "Hide", None))
        self.actionAdd.setText(_translate("MainWindow", "Add", None))

