# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qwordnotify.ui'
#
# Created: Tue May 20 20:23:23 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(338, 388)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.dictGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.dictGroupBox.setObjectName(_fromUtf8("dictGroupBox"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.dictGroupBox)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.dictListView = QtGui.QListView(self.dictGroupBox)
        self.dictListView.setObjectName(_fromUtf8("dictListView"))
        self.horizontalLayout_3.addWidget(self.dictListView)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.dictNewPushButton = QtGui.QPushButton(self.dictGroupBox)
        self.dictNewPushButton.setObjectName(_fromUtf8("dictNewPushButton"))
        self.verticalLayout_6.addWidget(self.dictNewPushButton)
        self.dictEditPushButton = QtGui.QPushButton(self.dictGroupBox)
        self.dictEditPushButton.setObjectName(_fromUtf8("dictEditPushButton"))
        self.verticalLayout_6.addWidget(self.dictEditPushButton)
        self.dictRemovePushButton = QtGui.QPushButton(self.dictGroupBox)
        self.dictRemovePushButton.setObjectName(_fromUtf8("dictRemovePushButton"))
        self.verticalLayout_6.addWidget(self.dictRemovePushButton)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_5.addWidget(self.dictGroupBox)
        self.settingsGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.settingsGroupBox.setObjectName(_fromUtf8("settingsGroupBox"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.settingsGroupBox)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.fileLabel = QtGui.QLabel(self.settingsGroupBox)
        self.fileLabel.setObjectName(_fromUtf8("fileLabel"))
        self.verticalLayout_2.addWidget(self.fileLabel)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.fileLineEdit = QtGui.QLineEdit(self.settingsGroupBox)
        self.fileLineEdit.setObjectName(_fromUtf8("fileLineEdit"))
        self.horizontalLayout_4.addWidget(self.fileLineEdit)
        self.optionsPushButton = QtGui.QPushButton(self.settingsGroupBox)
        self.optionsPushButton.setObjectName(_fromUtf8("optionsPushButton"))
        self.horizontalLayout_4.addWidget(self.optionsPushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.timeoutLabel = QtGui.QLabel(self.settingsGroupBox)
        self.timeoutLabel.setObjectName(_fromUtf8("timeoutLabel"))
        self.verticalLayout.addWidget(self.timeoutLabel)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.timeoutLineEdit = QtGui.QLineEdit(self.settingsGroupBox)
        self.timeoutLineEdit.setObjectName(_fromUtf8("timeoutLineEdit"))
        self.horizontalLayout_2.addWidget(self.timeoutLineEdit)
        self.savePushButton = QtGui.QPushButton(self.settingsGroupBox)
        self.savePushButton.setObjectName(_fromUtf8("savePushButton"))
        self.horizontalLayout_2.addWidget(self.savePushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.delayLabel = QtGui.QLabel(self.settingsGroupBox)
        self.delayLabel.setObjectName(_fromUtf8("delayLabel"))
        self.verticalLayout_3.addWidget(self.delayLabel)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.delayLineEdit = QtGui.QLineEdit(self.settingsGroupBox)
        self.delayLineEdit.setObjectName(_fromUtf8("delayLineEdit"))
        self.horizontalLayout.addWidget(self.delayLineEdit)
        self.startPushButton = QtGui.QPushButton(self.settingsGroupBox)
        self.startPushButton.setObjectName(_fromUtf8("startPushButton"))
        self.horizontalLayout.addWidget(self.startPushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addWidget(self.settingsGroupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 338, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuDict = QtGui.QMenu(self.menubar)
        self.menuDict.setObjectName(_fromUtf8("menuDict"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        MainWindow.setMenuBar(self.menubar)
        self.actionStart = QtGui.QAction(MainWindow)
        self.actionStart.setObjectName(_fromUtf8("actionStart"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionEdit = QtGui.QAction(MainWindow)
        self.actionEdit.setObjectName(_fromUtf8("actionEdit"))
        self.actionRemove = QtGui.QAction(MainWindow)
        self.actionRemove.setObjectName(_fromUtf8("actionRemove"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionAbout_Qt = QtGui.QAction(MainWindow)
        self.actionAbout_Qt.setObjectName(_fromUtf8("actionAbout_Qt"))
        self.menuFile.addAction(self.actionStart)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionPreferences)
        self.menuDict.addAction(self.actionNew)
        self.menuDict.addAction(self.actionEdit)
        self.menuDict.addAction(self.actionRemove)
        self.menuAbout.addAction(self.actionAbout)
        self.menuAbout.addAction(self.actionAbout_Qt)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuDict.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "qWordNotify", None))
        self.dictGroupBox.setTitle(_translate("MainWindow", "Dictionaries:", None))
        self.dictNewPushButton.setText(_translate("MainWindow", "Add", None))
        self.dictEditPushButton.setText(_translate("MainWindow", "Edit", None))
        self.dictRemovePushButton.setText(_translate("MainWindow", "Remove", None))
        self.settingsGroupBox.setTitle(_translate("MainWindow", "Settings:", None))
        self.fileLabel.setText(_translate("MainWindow", "File path:", None))
        self.optionsPushButton.setText(_translate("MainWindow", "Options", None))
        self.timeoutLabel.setText(_translate("MainWindow", "Message timeout (ms):", None))
        self.timeoutLineEdit.setText(_translate("MainWindow", "5000", None))
        self.savePushButton.setText(_translate("MainWindow", "Save", None))
        self.delayLabel.setText(_translate("MainWindow", "Message delay (s):", None))
        self.delayLineEdit.setText(_translate("MainWindow", "10", None))
        self.startPushButton.setText(_translate("MainWindow", "Start", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.menuDict.setTitle(_translate("MainWindow", "Dict", None))
        self.menuAbout.setTitle(_translate("MainWindow", "Help", None))
        self.actionStart.setText(_translate("MainWindow", "Start", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences", None))
        self.actionNew.setText(_translate("MainWindow", "New", None))
        self.actionEdit.setText(_translate("MainWindow", "Edit", None))
        self.actionRemove.setText(_translate("MainWindow", "Remove", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionAbout_Qt.setText(_translate("MainWindow", "About Qt", None))

